"use client";

import { useState } from "react";
import {
  Download,
  BarChart3,
  FileText,
  AlertTriangle,
  AlertCircle,
  Info,
  CheckCircle2,
} from "lucide-react";
import Card from "@/components/ui/card";
import type { ReportData, ReportSectionItem } from "@/types/knowledge";

interface ReportViewProps {
  data: ReportData;
  chatId?: string;
}

const PRIORITY_CONFIG = {
  High: {
    border: "border-l-red-500 dark:border-l-red-400",
    icon: AlertTriangle,
    iconColor: "text-red-600 dark:text-red-400",
    badge: "bg-red-50 text-red-700 dark:bg-red-500/10 dark:text-red-400",
  },
  Medium: {
    border: "border-l-amber-500 dark:border-l-amber-400",
    icon: AlertCircle,
    iconColor: "text-amber-600 dark:text-amber-400",
    badge: "bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-400",
  },
  Low: {
    border: "border-l-emerald-500 dark:border-l-emerald-400",
    icon: Info,
    iconColor: "text-emerald-600 dark:text-emerald-400",
    badge: "bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-400",
  },
} as const;

function getPriorityConfig(priority?: string) {
  if (priority && priority in PRIORITY_CONFIG) {
    return PRIORITY_CONFIG[priority as keyof typeof PRIORITY_CONFIG];
  }
  return null;
}

function SectionCards({ sections }: { sections: ReportSectionItem[] }) {
  if (!sections || sections.length === 0) return null;

  return (
    <div className="space-y-3">
      {sections.map((section, idx) => {
        const cfg = getPriorityConfig(section.priority);
        const Icon = cfg?.icon ?? Info;

        return (
          <div
            key={idx}
            className={`rounded-lg border border-zinc-200/80 border-l-4 bg-zinc-50 p-3.5 dark:border-white/[0.06] dark:bg-white/[0.02] ${
              cfg?.border ?? "border-l-zinc-300 dark:border-l-zinc-600"
            }`}
          >
            <div className="flex items-start gap-3">
              <div
                className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-md ${
                  cfg
                    ? `bg-white dark:bg-zinc-900 ${cfg.iconColor}`
                    : "bg-zinc-100 text-zinc-500 dark:bg-white/5 dark:text-zinc-400"
                }`}
              >
                <Icon className="h-3.5 w-3.5" />
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <p className="text-sm font-medium text-zinc-900 dark:text-zinc-100">
                    {section.header}
                  </p>
                  {section.priority && (
                    <span
                      className={`rounded-md px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${
                        cfg?.badge ?? "bg-zinc-100 text-zinc-600 dark:bg-white/5 dark:text-zinc-400"
                      }`}
                    >
                      {section.priority}
                    </span>
                  )}
                </div>
                <p className="mt-1 text-xs leading-relaxed text-zinc-600 dark:text-zinc-400">
                  {section.content}
                </p>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}

function RecommendationList({ items }: { items: string[] }) {
  if (!items || items.length === 0) return null;

  return (
    <ul className="space-y-2">
      {items.map((rec, idx) => (
        <li
          key={idx}
          className="flex items-start gap-2.5 rounded-lg bg-zinc-50 px-3.5 py-2.5 dark:bg-white/[0.02]"
        >
          <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-500" />
          <p className="text-sm text-zinc-900 dark:text-zinc-100">{rec}</p>
        </li>
      ))}
    </ul>
  );
}

function reportToMarkdown(data: ReportData): string {
  const lines: string[] = [];
  lines.push(`# ${data.title ?? "Business Analysis Report"}`);
  lines.push("");

  if (data.summary) {
    lines.push("## Summary");
    lines.push("");
    lines.push(data.summary);
    lines.push("");
  }

  if (data.sections && data.sections.length > 0) {
    lines.push("## Key Findings");
    lines.push("");
    for (const section of data.sections) {
      const badge = section.priority ? ` [${section.priority}]` : "";
      lines.push(`### ${section.header}${badge}`);
      lines.push("");
      lines.push(section.content);
      lines.push("");
    }
  }

  if (data.recommendations && data.recommendations.length > 0) {
    lines.push("## Recommendations");
    lines.push("");
    for (const rec of data.recommendations) {
      lines.push(`- ${rec}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by InventraAI on ${new Date().toLocaleDateString()}*`);
  return lines.join("\n");
}

export default function ReportView({ data, chatId }: ReportViewProps) {
  const [downloading, setDownloading] = useState(false);

  const handleDownload = async () => {
    setDownloading(true);
    try {
      if (chatId) {
        const res = await fetch(
          `${process.env.NEXT_PUBLIC_API_URL}/ai/knowledge/chat/export/${chatId}`,
          { credentials: "include" },
        );
        if (!res.ok) throw new Error("PDF export failed");
        const blob = await res.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${(data.title ?? "business-report").toLowerCase().replace(/[^a-z0-9]+/g, "-")}.pdf`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
        return;
      }

      // Fallback — markdown download when no chatId
      const markdown = reportToMarkdown(data);
      const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      const filename = (data.title ?? "ai-report")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "");
      link.href = url;
      link.download = `${filename}.md`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch {
      // fallback — copy to clipboard
      const markdown = reportToMarkdown(data);
      await navigator.clipboard.writeText(markdown);
    } finally {
      setDownloading(false);
    }
  };

  return (
    <Card className="overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-zinc-200/80 px-5 py-4 dark:border-white/[0.08]">
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-50 dark:bg-emerald-500/10">
            <FileText className="h-4.5 w-4.5 text-emerald-600 dark:text-emerald-400" />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
              {data.title ?? "Business Analysis Report"}
            </h3>
            <p className="text-xs text-zinc-500 dark:text-zinc-400">
              AI-generated insights from your documents
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleDownload}
            disabled={downloading}
            className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-200/80 bg-white px-3 py-1.5 text-xs font-medium text-zinc-700 transition-colors hover:bg-zinc-50 disabled:opacity-60 dark:border-white/10 dark:bg-white/5 dark:text-zinc-300 dark:hover:bg-white/10"
          >
            <Download className="h-3.5 w-3.5" />
            {downloading ? "Saving..." : "Download"}
          </button>
          <button
            type="button"
            disabled
            className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-200/80 bg-white px-3 py-1.5 text-xs font-medium text-zinc-600 opacity-60 cursor-not-allowed dark:border-white/10 dark:bg-white/5 dark:text-zinc-400"
          >
            <BarChart3 className="h-3.5 w-3.5" />
            Charts
          </button>
        </div>
      </div>

      {/* Body */}
      <div className="space-y-5 p-5">
        {data.summary && (
          <div className="rounded-lg bg-emerald-50/60 p-4 dark:bg-emerald-500/5">
            <p className="text-sm leading-relaxed text-zinc-800 dark:text-zinc-300">
              {data.summary}
            </p>
          </div>
        )}

        <SectionCards sections={data.sections ?? []} />
        <RecommendationList items={data.recommendations ?? []} />
      </div>
    </Card>
  );
}
